<!doctype html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7 ]>   <html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]>   <html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]>   <html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <title>KeyRights — установка приложения</title>
    <link rel='stylesheet' href='/static/css/style.css' />
    <script type="text/javascript" src="//api.bitrix24.com/api/v1/"></script>
</head>
<body>
<?
$model = SibirixKeyrightsBackend_Model_Api::getInstance();
$info = $model->callMethod('app.info');
//echo("<pre>");print_r($info);echo("</pre>");
?>
<script>
    var CONST = {
        BX24: {
            ENTITY: 'keyrights',
            USER_PASS_NAME: 'passPhrase',
            USER_PASS_ENTITY: 'keyrights.user'
        }
    };

    function tryInstallFinish(form) {
        var input = document.getElementById('kr_passphrase');
        var parent = input.parentElement;
        var key = input.value;
        parent.className = '';
        if (!key.length) {
            parent.className = 'has-error';
            input.focus();
            return false;
        }

        form.style.display = 'none';

        BX24.callMethod(
            'entity.item.get',
            { ENTITY: CONST.BX24.USER_PASS_ENTITY, NAME: CONST.BX24.USER_PASS_NAME},
            function(result) {
                if (result.answer.result && (result.answer.result.length > 0)) {
                    // already exists, do nothing
                    doInstallFinish();
                } else {
                    BX24.callMethod(
                        'entity.item.add',
                        { ENTITY: CONST.BX24.USER_PASS_ENTITY, NAME: CONST.BX24.USER_PASS_NAME, PREVIEW_TEXT: key },
                        function (/* result */) {
                            doInstallFinish();
                        }
                    );
                }
            }
        );

        return false;
    }

    function doInstallFinish() {
        BX24.installFinish();
    }
</script>

<div class="splash">
    <?= $this->partial('_partials/install/texts.phtml') ?>
    <form method="post" onsubmit="return tryInstallFinish(this)" id="kr_install_form">
        <div class="">
            <input type="password" id="kr_passphrase" class="form-control" placeholder="Введите ключ-фразу для шифрации паролей">
        </div>
        <input type="submit" class="btn btn-default" value="Завершить установку">
    </form>
</div>

<div class="eula">Завершая установку, вы соглашаетесь с <a href="https://drive.google.com/open?id=0B2Ggj_E1AyWRZENyRFByVlpMNjQ" target="_blank">лицензионным соглашением</a> и политикой обработки персональных данных.</div>

</body>
</html>
