<!doctype html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7 ]>   <html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]>   <html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]>   <html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <title>KeyRights главная!</title>
    <link rel='stylesheet' href='/css/style.css' />
    <script type="text/javascript" src="//api.bitrix24.com/api/v1/"></script>
</head>

<body class="installer">
<div class="splash">
    <div class="logo">
        <img src="/images/big-logo.png" title="KeyRights — парольник от студии «Сибирикс»">
    </div>
    <div class="texts">
        <p>Создавайте разделы и&nbsp;подразделы <span class="icon tree"></span></p>
        <p>Добавляйте&nbsp;или импортируйте пароли <span class="icon pass"></span></p>
        <p>Задавайте необходимые уровни доступа <span class="icon rights"></span></p>
    </div>

    <a href="/" class="go-next btn btn-default btn-lg">Продолжить</a>
</div>

<script src="/bower_components/jquery/dist/jquery.min.js"></script>

<script src="/js/plugins/polyfills/Array.prototype.findIndex.js"></script>

<script src="/js/libs/jquery-migrate-1.2.1.min.js"></script>
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/bower_components/angular/angular.min.js"></script>
<script src="/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
<script src="/js/plugins/ui-bootstrap-tpls-0.11.0.min.js"></script>
<script src="/js/plugins/angular-locale_ru-ru.js"></script>
<script src="/js/plugins/mousetrap.js"></script>
<script src="/js/plugins.js"></script>
<script src="/js/helpers.js"></script>
<script src="/js/main.js"></script>

<script>
    fitWindow();
</script>
</body>
</html>
