<div class="sprintTaskList">
    <div class="header">
        <div class="fakeHandle packetFormer jsPacketFormerHandle" title="<?= $this->t('SPRINT_PACKET_FORMER_HANDLE'); ?>"></div>
        <div class="overflow small-2 small-1">
            <div class="feed-post-menu-but menuIcon jsSpritGridMenu popupOpener taskMenu"></div>
            <div class="grid-sort-rank jsGridSortRank" title="<?= $this->t('SPRINT_GRID_SORT'); ?>"></div>
            <div class="gridTaskFilter gridTadkTypeFilter jsGridTaskFilter"><select name="taskFilter" class="empty" multiple='multiple' data-placeholder=" " placeholder=" "></select></div>
            <div class="gridTaskFilter gridTaskTitleFilter jsGridTaskTitleFilter"><input type="text" placeholder="<?= $this->t('SPRINT_GRID_TITLE_FILTER_PLACEHOLDER'); ?>"></div>
            <div class="gridTaskFilter gridTaskStatusFilter jsGridTaskStatusFilter"><select name="taskFilterStatus" class="empty" multiple='multiple' data-placeholder=" " placeholder=" "></select></div>
            <div class="gridTaskFilter gridTaskFilterBehavior jsGridTaskFilterBehavior" title="<?= $this->t('SPRINT_GRID_FILTER_BEHAVIOR'); ?>"><select name="taskFilterBehavior" class="empty" data-placeholder=" " placeholder=" "><option value="fade"><?= $this->t('TO_DARKEN'); ?></option><option value="hide"><?= $this->t('TO_HIDE'); ?></option></select></div>
        </div>
    </div>
    <div class="grid" id="sprintTaskList"></div>
</div>
