<div class="sidepanel detail detail-password edit" ng-controller="EditPassCtrl" tabcycle ng-show="visible">
    <div class="js-baron wrapper wrapper-right">
        <div class="scroller" style="height: 500px;">
            <div class="rel">
                <table class="table sidepanel-header">
                    <thead>
                    <tr>
                        <th colspan="2"><span class="favicon" favicon="formData.CRYPTED.URL"><img src="<?= KEYRIGHTS_PATH_STATIC; ?>/images/no-icon.ico" alt="" class="no-icon"></span>
                            <span class="one-line long" ng-show="formData.NAME">{{formData.NAME}}</span>
                            <span class="one-line" ng-show="!formData.NAME"><?= $this->t('PASS_NEW'); ?></span> </th>
                    </tr>
                    </thead>
                </table>

                <form name="editPassForm" novalidate ng-submit="!showLoader && isFormValid() && submit()">
                <table class="table pass-info">
                    <tbody>
                    <tr>
                        <td><?= $this->t('NAME'); ?></td>
                        <td><input type="text" required ng-model="formData.NAME" class="form-control" value="{formData.NAME}" ng-keyup="closeOnEsc($event)" ng-focus="rememberLastField($event)" ng-blur="clearLastField($event)" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->t('LOGIN'); ?></td>
                        <td><input type="text" ng-model="formData.CRYPTED.LOGIN" class="form-control" value="{formData.CRYPTED.LOGIN}" ng-keyup="closeOnEsc($event)" ng-focus="rememberLastField($event)" ng-blur="clearLastField()" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->t('PASS'); ?> <i class="icon-eye"
                            ng-click="passInputType = (passInputType == 'text' ? 'password' : 'text')"
                            ng-class="{'opened': passInputType === 'text'}"></i></td>
                        <td><input type="{{passInputType}}" ng-model="formData.CRYPTED.PASSWORD" class="form-control" ng-keyup="closeOnEsc($event)"
                            value="{formData.CRYPTED.PASSWORD}" ng-focus="rememberLastField($event)" ng-blur="clearLastField()" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->t('REPEAT'); ?></td>
                        <td ng-class="{'has-error': !isPasswordsEqual()}"><input type="{{passInputType}}" ng-model="formData.CRYPTED.PASSWORD_CONFIRM" ng-keyup="closeOnEsc($event)"
                            class="form-control" value="{formData.CRYPTED.PASSWORD}" ng-disabled="passInputType == 'text'" ng-focus="rememberLastField($event)" ng-blur="clearLastField()" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->t('DIFFICULT'); ?></td>
                        <td><span class="label {{ passStrength.class }}">{{ passStrength.title }}</span><a href="javascript:void(0);" class="pass-gen" ng-click="generatePass()" ng-keyup="closeOnEsc($event)"><i
                                class="glyphicon glyphicon-repeat"></i><?= $this->t('GENERATE_PASS'); ?></a></td>
                    </tr>
                    <tr>
                        <td><?= $this->t('URL'); ?></td>
                        <td><input type="text" ng-model="formData.CRYPTED.URL" class="form-control" value="{formData.CRYPTED.URL}" ng-keyup="closeOnEsc($event)" ng-focus="rememberLastField($event)" ng-blur="clearLastField()" /></td>
                    </tr>
                    <!--tr>
                        <td>Истекает</td>
                        <td><input type="checkbox"
                                   ng-checked="formData.CRYPTED.EXPIRED"
                                   ng-click="dateCheckboxClick($event)"
                            /><label datepicker-popup="{{format}}"
                                   ng-model="formData.CRYPTED.EXPIRED"
                                   is-open="opened"
                                   datepicker-options="dateOptions"
                                   ng-required="true"
                                   close-text="Закрыть"
                                   clear-text="Очистить"
                                   current-text="Сегодня"
                                   min-date="{{today}}"
                                   ng-click="opened = !opened;"
                            >{{formData.CRYPTED.EXPIRED ? formatDate(formData.CRYPTED.EXPIRED) : 'выберите дату и время'}}</label></td>
                    </tr-->
                    </tbody>
                </table>

                <div class="note">
                    <div class="note-header"><?= $this->t('NOTE'); ?>:</div>
                    <textarea class="form-control" ng-model="formData.CRYPTED.NOTE" my-maxlength="10000" ng-focus="rememberLastField($event)" ng-blur="clearLastField()" ng-keyup="closeOnEsc($event)"></textarea>
                    <input type="submit" class="btn btn-primary" value="<?= $this->t('SAVE'); ?>" ng-class="{'disabled': showLoader || !isFormValid()}">
                    <a href="javascript:void(0);" class="btn btn-default" ng-click="cancel()"><?= $this->t('CANCEL'); ?></a>
                    <div class="loader" ng-show="showLoader"></div>
                </div>
                </form>

                <!--div ng-controller="PassFileCtrl" class="note files">
                    <div class="note-header">Файлы:</div>

                    <p ng-repeat="file in files">
                        <a href="javascript:void(0);">{{file.NAME}}</a><i class="icon-remove" title="Удалить">&nbsp;</i>
                    </p>

                    <div ng-show="uploading" class="progress progress-striped active">
                        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                            <span class="sr-only">0% завершено</span>
                        </div>
                    </div>

                    <div class="js-upload-pass"></div>
                </div-->
            </div>
        </div>
        <div class="scroller-bar-wrapper">
            <div class="scroller-bar"></div>
        </div>
    </div>
</div>
