<div class="sidepanel detail" ng-controller="FolderInfoCtrl" ng-show="isVisible">
    <div class="js-baron wrapper wrapper-right">
        <div class="scroller" style="height: 500px;">
            <div class="rel">
                <table class="table sidepanel-header">
                    <thead>
                        <tr>
                            <th>
                                <i class="icon-folder {{(folder.DETAIL_PICTURE ? '' : 'icon-folder-sprite folder-' + folder.DESCRIPTION)}}"
                                   style="{{(folder.DETAIL_PICTURE ? 'background-image: url(\'' + folder.DETAIL_PICTURE + '\');' : '')}}">&nbsp;</i>
                                <span class="one-line" title="{{folder.NAME}}">{{folder.NAME}}</span>
                            </th>
                            <th class="edit-link">
                                <a role="presentation" ng-show="folder.ID > 0"
                                   ng-click="edit(folder.ID)"
                                   ng-show="canEditRights(folder.ID)"
                                   data-toggle="modal"
                                   data-target="#sectionAdd"
                                   href="javascript:void(0);"><?= $this->t('EDIT'); ?></a></th>
                        </tr>
                    </thead>
                </table>

                <?= $this->render('panel-right-rights.phtml'); ?>
            </div>
        </div>
        <div class="scroller-bar-wrapper">
            <div class="scroller-bar"></div>
        </div>
    </div>
</div>
