<?
$MESS["DISK_HELP_1"] = "<strong>Drive</strong> est le stockage de fichiers ultime et une solution de partage de rationaliser les processus d'affaires de votre entreprise, disponibles à l'intérieur de votre compte Bitrix24.";
$MESS["DISK_HELP_10"] = "Il y a plusieurs façons aller chercher de nouveaux documents dans votre lecteur. D'abord, vous pouvez simplement cliquer sur le bouton Ajouter. Ceux qui préfèrent glisser-déposer des fichiers à partir d'une fenêtre de l'Explorateur peut certainement faire ça. Pour créer un nouveau document à partir de l'intérieur de votre compte Bitrix24, cliquez sur 'File' puis 'Créer en utilisant', GoogleDocs sélection, Web App MS Office, ou tout autre logiciel de suite bureautique installés sur votre ordinateur (comme Microsoft Office, Mac Pages, Open Office, etc).";
$MESS["DISK_HELP_11"] = "Quel est Bitrix24.Drive ?";
$MESS["DISK_HELP_12"] = "Bitrix24.Drive enregistre vos fichiers à la fois localement et dans le nuage. Une fois que vous enregistrez un document, la copie stockée dans le nuage est automatiquement synchronisé pour correspondre à la nouvelle version. Il fonctionne comme par magie - Bitrix24.Drive vous évite les tracas de téléchargement et le téléchargement de fichiers. Ouvrir un fichier, modifier et proche - tout comme vous le feriez lors de l'édition d'un fichier sur votre ordinateur. La dernière version du document sera disponible pour vous et vos collègues de travail dans le cloud, sur leurs ordinateurs et appareils mobiles. Il suffit de télécharger Bitrix24 application de bureau et connectez votre Bitrix24.Drive d'avoir accès à plusieurs fonctions de AutoSync de l'appareil.";
$MESS["DISK_HELP_13"] = "Partage de documents";
$MESS["DISK_HELP_14"] = "Utilisez Actions pour discuter des travaux et des documents. Commencez par taper un message et attacher un fichier à partir du lecteur. Terminé ? Cliquez sur 'Envoyer'. Vos collègues peuvent maintenant afficher ou modifier le document que vous avez joint, si vous leur donniez l'autorisation. Chaque fois que quelqu'un enregistre une nouvelle version du fichier, une notification commentaire est ajouté à votre message d'origine, et le fichier joint est mis à jour. L'histoire de modification du fichier est conservé; les utilisateurs peuvent voir toutes les révisions précédentes effectuées au fichier et de revenir à une version plus ancienne, si nécessaire.";
$MESS["DISK_HELP_17"] = "Document Tracking utilisation";
$MESS["DISK_HELP_18"] = "Documents à l'intérieur Bitrix24 peuvent être utilisés dans une entité qui permet de pièces jointes (Activité Stream, tâches, évènements de calendrier, CRM). Vous pouvez afficher les entités où le fichier est utilisé et les utilisateurs qui ont accès dans les propriétés du document (Fichier> Ouvrir). Notez qu'une fois que vous supprimez un fichier de votre disque dur, vous le supprimiez de toutes les entités Bitrix24 il a été attaché à ainsi.";
$MESS["DISK_HELP_19"] = "La ligne du bas est - quand il vient à travailler avec des documents <strong>Bitrix24.Drive</strong> est votre meilleur ami que vous pouvez toujours compter sur. En savoir plus sur Drive, dans le cours de formation.";
$MESS["DISK_HELP_2"] = "Gestion des fichiers et des dossiers";
$MESS["DISK_HELP_3"] = "Créer un nouveau document";
$MESS["DISK_HELP_4"] = "Quel est Bitrix24 Drive ?";
$MESS["DISK_HELP_5"] = "Partage de documents";
$MESS["DISK_HELP_6"] = "Document Tracking utilisation";
$MESS["DISK_HELP_7"] = "Gestion des fichiers et des dossiers";
$MESS["DISK_HELP_8"] = "Dur présente de façon simple et facile à parcourir les fichiers et dossiers, et de travailler avec eux. Vous avez deux options pour l'affichage et la navigation de vos documents. Premièrement, il ya une arborescence familier qui organise vos fichiers de manière hiérarchique. Deuxièmement, il ya une vue sur la tuile qui met tous vos fichiers et dossiers sur une seule page. Quelle que soit la façon dont fonctionne le mieux pour vous, le passage d'un mode à l'autre se fait en un seul clic.";
$MESS["DISK_HELP_9"] = "Créer un nouveau document";
?>