<? global $APPLICATION; ?>
<? ob_start() ?>
    <script type="text/javascript" data-skip-moving="true">
        /**
         * Константы
         */
// Права доступа
        CONST = {};
        CONST.ACCESS = {
            NO: 0,
            CAN_READ: 1,
            CAN_WRITE: 2,
            CAN_OWN: 3
        };

        CONST.BX24 = {
            ENTITY: 'keyrights',
            USER_PASS_NAME: 'passPhrase',
            USER_PASS_ENTITY: 'keyrights.user'
        };

        CONST.backend = '<?= APPLICATION_BACKEND; ?>';

        CONST.appDomain = "";
        CONST.isAdmin = 1;
        CONST.staticPath = '<?= KEYRIGHTS_PATH_STATIC; ?>/';
        CONST.translator = <?= $this->modelOutput($this->t()->getMessages()); ?>;
        <? $keyModel = new SibirixKeyrightsBackend_Model_Entity(); ?>
        <? $keyPass = $keyModel->callMethod('entity.item.get', array('ENTITY' => 'keyrightsuser', 'NAME' => 'passPhrase' )) ?>
        CONST.key = '<?= $keyPass[0]['PREVIEW_TEXT'] ?>';

        <? $userModel = new SibirixKeyrightsBackend_Model_User();
            $userData = $userModel->getUserData(); ?>

        window.userData = <?= $this->modelOutput($userData); ?>;
        window.csrfToken = '<?= bitrix_sessid(); ?>';

        window.String._ = function(messageId) {
            if (window.CONST && window.CONST.translator && window.CONST.translator[messageId]) {
                return window.CONST.translator[messageId];
            }
            return messageId;
        };
    </script>
<? $str = ob_get_clean() ?>

<? $this->asset()->addHeadString($str) ?>

    <div id="keyrights" class="standalone"></div>

<?
$this->asset()->addCss(KEYRIGHTS_PATH_STATIC . '/css/style.css');
$this->asset()->addJs(KEYRIGHTS_PATH_STATIC . '/js/libs/aes.js');
$this->asset()->addJs(KEYRIGHTS_PATH_STATIC . '/js/libs/papaparse.js');
?>

<?
$this->asset()->addJs(KEYRIGHTS_PATH_STATIC . '/js/bundle.js');
?>

<?/*<script src="http://192.168.0.101:8032/webpack-dev-server.js"></script>
<script src="http://192.168.0.101:8032/static/js/bundle.js"></script>*/?>
