<div class="jsBacklogPanel backlogPanel fixedPanel">
    <div class="panelButton jsBacklogOpenButton"><span><?= $this->t("SPRINTS"); ?></span></div>

    <div class="panelBody">
        <div class="header">
            <a class="hide jsPanelHide"></a>
            <div class="title"><?= $this->t("SPRINTS"); ?></div>
        </div>

        <div class="body">
            <div class="field">
                <div class="label"><?= $this->t("SPRINT"); ?></div>
                <div class="value">
                    <div class="jsBacklogSprintSelector"></div>
                </div>
            </div>

            <div class="field sprint-add">
                <div class="label"><a href="javascript:void(0)" class="show-form js-show-form">Добавить спринт</a></div>
                <div class="value sprint-add-form js-sprint-add-form">
                    <div class="title"><input type="text" name="sprintTitle" placeholder="Название спринта"></div>
                    <div class="buttons">
                        <div class="thin-green-button jsSprintAddOk">Ок</div>
                        <a class="cancelLink jsSprintAddCancel">Отмена</a>
                    </div>
                </div>
                <div class="sprint-loader" style="text-align: center;display: none"><canvas class="shortLoader"></canvas></div>
            </div>

            <div class="field">
                <div class="value">
                    <label><?= $this->t("SPRINTS_SHOW_FINISHED"); ?> <input type="checkbox" class="show-ended"></label>
                </div>
            </div>

            <div class="icons">
                <div class="right miniblock hours" title="<?= $this->t('SPRINTS_TIME_STATS'); ?>"><b></b>0/0</div>
                <div class="left miniblock subtasks" title="<?= $this->t('SPRINTS_TASK_COUNT'); ?>"><b></b>0</div>
                <div class="clear"></div>
            </div>

            <div class="scrollBlock jsBacklogScrollArea"></div>
        </div>
        <div class="resizer resizer-bottom"><i></i></div>
    </div>
</div>

<?= $this->partial('ejs/panel/backlog/sprint-selector.ejs'); ?>
<?= $this->partial('ejs/panel/backlog/sprint-selector.ejs'); ?>
