<div ng-controller="ChangeOwnerCtrl"
     class="modal fade change-owner"
     id="change-owner"
     tabindex="-1"
     role="dialog"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content add-user">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                <h4 class="modal-title">
                    <?= $this->t('OWNER_CHANGING'); ?> {{'section' === type && '<?= $this->t('OWNER_CHANGING_SECTION'); ?>' || '<?= $this->t('OWNER_CHANGING_PASS'); ?>'}}:
                    <span class="directory">
                        <i ng-if="type == 'section'" class="icon-folder {{(item.DETAIL_PICTURE ? '' : 'icon-folder-sprite folder-' + item.DESCRIPTION)}}"
                                               style="{{(item.DETAIL_PICTURE ? 'background-image: url(\'' + item.DETAIL_PICTURE + '\');' : '')}}">&nbsp;</i>
                        <span ng-if="type == 'password'" class="favicon" favicon="item.CRYPTED.URL"><img src="<?= KEYRIGHTS_PATH_STATIC; ?>/images/no-icon.ico" alt="" class="no-icon"></span>
                        {{item.NAME}}</span>
                </h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <form action="javascript:void(0)" class="form-horizontal" role="form">
                        <div class="search-wrapper">
                            <input type="text" class="form-control" id="filter-users-owner"
                                   value="{queryUser}"
                                   ng-model="queryUser">
                            <i class="icon-search"></i>
                        </div>
                    </form>
                    <div class="tab-pane" id="users">
                        <div class="user-add-collapsible-list">
                            <ul>
                                <li ng-repeat="user in users | filterByActive: userFilterActive | filterByFio: queryUser" ng-class="{selected: user.ID === idNewOwner}">
                                    <a ng-click="select(user.ID)" href="javascript:void(0)">
                                        [{{user.ID}}] {{user.NAME}} {{user.LAST_NAME}} ({{user.EMAIL}})
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button ng-disabled="showLoader" type="button" class="btn btn-default" data-dismiss="modal"><?= $this->t('CANCEL2'); ?></button>
                <a ng-click="save()"
                   ng-disabled="!idNewOwner || showLoader"
                   class="btn btn-primary"><?= $this->t('SAVE'); ?><span ng-show="showLoader" class="loader"></span></a>
            </div>
        </div>
    </div>
</div>
