<div class="modal fade confirm-dialog" id="dialogConfirm" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="javascript:void(0);" name="sectionForm" ng-controller="DialogConfirmCtrl" ng-submit="ok()">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{{data.title}}</h4>
                </div>
                <div class="modal-body">{{data.text}}</div>
                <div class="modal-footer">
                    <a href="javascript:void(0);" class="btn btn-default" data-dismiss="modal"><?= $this->t('CANCEL'); ?></a>
                    <button class="btn btn-default">OK</button>
                </div>
            </form>
        </div>
    </div>
</div>
