<div class="modal fade ok-dialog" ng-class="{ loading: showLoader }" id="dialogOk" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="javascript:void(0);" name="sectionForm" ng-controller="DialogOkCtrl" ng-submit="ok()">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" ng-bind-html="data.title"></h4>
                </div>
                <div class="modal-body">{{data.text}}</div>
                <div class="modal-body" ng-if="data.showReportSend"><a href="#" ng-click="sendReport()"><?= $this->t('SEND_REPORT'); ?></a></div>
                <div class="modal-footer">
                    <button class="btn btn-default">OK</button>
                </div>
            </form>
            <div class="loader-overlay"><div class="loader"></div></div>
        </div>
    </div>
</div>
