<div ng-controller="ImportCtrl"
     class="modal fade"
     id="import-passwords"
     tabindex="-1"
     role="dialog"
     data-backdrop="static"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content add-user">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                <h4 class="modal-title"><?= $this->t('IMPORT'); ?></h4>
            </div>

            <div class="modal-body" ng-show="!!fileData">{{ fileData.name }} ({{ getHumanFileSize(fileData.size) }})</div>
            <input type="file" style="display:none" id="file" name='file'
                   onchange="angular.element(this).scope().fileNameChanged(this)">

            <div class="progress progress-striped active" ng-show="processing">
                <div class="progress-bar jsImportProgressbar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    0%
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->t('CANCEL2'); ?></button>
                <button ng-click="action($event)"
                        type="button"
                        class="btn btn-primary">{{state}}</button>
            </div>
            <div class="loader" ng-show="showLoader"></div>
        </div>
    </div>
</div>
