<div ng-controller="AddUserCtrl"
     class="modal fade"
     id="add-user"
     tabindex="-1"
     role="dialog"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content add-user">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                <h4 class="modal-title">
                    {{rightsType && '<?= $this->t('PROHIBIT'); ?>' || '<?= $this->t('GRANTING'); ?>'}} <?= $this->t('ACCESS_TO'); ?> {{'section' === type && '<?= $this->t('ACCESS_TO_SECTION'); ?>' || '<?= $this->t('ACCESS_TO_PASS'); ?>'}}:
                    <span class="directory"><span class="dir-icon" style=""></span> {{item.NAME}}</span>
                </h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-7">
                        <ul class="js-tabs nav nav-tabs">
                            <li class="active"><a href="#groups" ng-click="showTab($event)"><?= $this->t('GROUPS'); ?></a></li>
                            <li><a href="#users" ng-click="showTab($event)"><?= $this->t('USERS'); ?></a></li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active" id="groups">
                                <form action="javascript:void(0)" class="form-horizontal" role="form">
                                    <div class="search-wrapper">
                                        <input type="text" class="form-control" id="filter-groups"
                                            value="{queryGroup}"
                                            ng-model="queryGroup">
                                        <i class="icon-search"></i>
                                    </div>
                                </form>

                                <div class="user-add-collapsible-list">
                                    <groups groups="groups" query="queryGroup"></groups>
                                </div>
                            </div>

                            <div class="tab-pane" id="users">
                                <form action="javascript:void(0)" class="form-horizontal" role="form">
                                    <div class="search-wrapper">
                                        <input type="text" class="form-control" id="filter-users"
                                            value="{queryUser}"
                                            ng-model="queryUser">
                                        <i class="icon-search"></i>
                                    </div>
                                </form>
                                <div class="user-add-collapsible-list">
                                    <ul>
                                        <li ng-repeat="user in users | filterByActive: userFilterActive | filterByFio: queryUser"
                                            ng-click="toggleItem(user.ID, USER_TYPE)"
                                            ng-class="{selected: isAdded(user.ID, USER_TYPE)}">
                                            <a href="javascript:void(0)">
                                                [{{user.ID}}] {{user.NAME}} {{user.LAST_NAME}} ({{user.EMAIL}})
                                                <span class="plus glyphicon glyphicon-plus" title="<?= $this->t('ADD'); ?>"></span>
                                                <span class="minus glyphicon glyphicon-minus" title="<?= $this->t('DEL'); ?>"></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="right-col col-md-5">
                        <div class="added-list">
                            <div class="added"><?= $this->t('ADDED'); ?> ({{rights.length}})</div>

                            <div ng-repeat="right in rights" class="added-items">
                                <a ng-click="removeItem(right.item.ID, right.type)"
                                   href="javascript:void(0)" title="<?= $this->t('DEL'); ?>">
                                    <span class="delete">x</span>
                                    {{right.item.NAME || right.item.LAST_NAME
                                        ? right.item.NAME + ' ' + right.item.LAST_NAME
                                        : right.item.EMAIL}}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->t('CANCEL2'); ?></button>
                <button ng-click="save()"
                        type="button"
                        class="btn btn-primary"><?= $this->t('SAVE'); ?></button>
            </div>
        </div>
    </div>
</div>
