<?
$MESS["DISK_HELP_1"] = "<strong>Dysk</strong> jest ostatecznym schowkiem do plików, a rozwiązanie współdzielenia dostępne wenątrz twojego konta Bitrix24, aby usprawnić w twojej firmie operacje na dokumentach.";
$MESS["DISK_HELP_10"] = "Jest kilka sposobów na dodanie nowych dokumentów do twojego Dysku. Pierwszy, możesz po prostu kliknąć przycisk Dodaj. Możesz również przeciągnąć pliki z menadżera plików, jak Explorer. Aby utworzyć nowy dokument z poziomu konta Bitrix24, kliknij 'Nowy dokument', a następnie 'Utwórz używając', wybierając Google Docs, MS Office Web App lub jakikolwiek pakiet office zainstalowany na twoim komputerze (jak Microsoft Office, Mac Pages, Open Office, itp.).";
$MESS["DISK_HELP_11"] = "Czym jest Bitrix24.Drive?";
$MESS["DISK_HELP_12"] = "Bitrix24.Drive jest kompletnym systemem przechowywania, synchronizowania, edytowania i udostępniania plików. Sparowany z desktopową aplikacją, Bitrix24.Drive pozwala na przechowywanie plików zarówno w chmurze, jak i lokalnie. Jeżeli modyfikujesz dokument na swoim komputerze lub urządzeniu, kopia przechowywana w chmurze zostanie automatycznie zsynchronizowana z nową wersją. Działa cuda - Bitrix24.Drive oszczędza ci trudu pobierania i dodawania plików. Otwórz plik, edytuj i zamknij - dokładnie tak samo jak przy edytowaniu pliku na komputerze. Najnowsza wersja dokumentu będzie dostępna dla ciebie i twoich współpracowników zarówno w chmurze, jak i na ich komputerach i urządzeniach mobilnych. Po prostu pobierz aplikację desktopową Bitrix24 i połącz swój Bitrix24.Drive, aby uzyskać dostęp wielozadaniowego urządzenia z autosynchronizacją.";
$MESS["DISK_HELP_13"] = "Udostępnianie dokumentów";
$MESS["DISK_HELP_14"] = "Możesz użyć Tablicy, aby udostępnić dokumenty i jednocześnie je omawiać. Zacznij od napisania wiadomości i dołączenia do niej pliku z Dysku. Następnie kliknij 'Wyślij'. Teraz twoi koledzy mogą przeglądać lub edytować załączony dokument, jeżeli właśnie takie zostały im dane uprawnienia. Za każdym razem gdy ktoś zapisuje nową wersję pliku, powiadomienie w formie komentarza jest dodawane do oryginalnej wiadomości, a dołączony plik jest aktualizowany. Historia modyfikacji pliku jest zachowana, a użytkownicy mogą przeglądać wszystkie poprzednie wersje pliku i przywracać starszą wersję, jeżeli to konieczne.";
$MESS["DISK_HELP_17"] = "Śledzenie dokumentu";
$MESS["DISK_HELP_18"] = "Dokumenty w Bitrix24 mogą być wykorzystywane w każdej jednostce, która pozwala na załączanie plików (Tablica, Zadania, Kalendarz wydarzeń, CRM). We właściwościach dokumentu (Plik > Otwórz) możesz wyświetlić jednostki, w których plik jest wykorzystywany i którzy użytkownicy mają do nich. Zauważ, że gdy usuniesz plik ze swojego Dysku usuniesz go również z jednostek Bitrix24, do których zostały załączone.";
$MESS["DISK_HELP_19"] = "Dolna linia jest taka - kiedy przychodzi do pracy z dokumentami, <strong>Bitrix24.Drive</strong> jest twoim najlepszym przyjacielem, na którym możesz zawsze polegać. Przeczytaj więcej o Dysku w kursie treningowym.";
$MESS["DISK_HELP_2"] = "Zarządzanie plikami i folderami";
$MESS["DISK_HELP_3"] = "Tworzenie Nowego Dokumentu";
$MESS["DISK_HELP_4"] = "Czym jest Bitrix24.Drive?";
$MESS["DISK_HELP_5"] = "Udostępnione dokumenty";
$MESS["DISK_HELP_6"] = "Śledzenie dokumentu";
$MESS["DISK_HELP_7"] = "Zarządzanie plikami i folderami";
$MESS["DISK_HELP_8"] = "Funkcje Dysku to nieskomplikowany i prosty sposób na przeglądanie plików i folderów oraz na działanie na nich. Masz dwie opcje umożliwiające wyświetlanie dokumentów i nawigowanie po nich. Pierwsza to znany widok tabeli, który porządkuje twoje pliki w sposób hierarchiczny. Druga to widok kafelkowy, który umieszcza wszystkie twoje pliki i foldery na jednej stronie. Którykolwiek uznasz za lepszy dla siebie, przełączenie z jednego trybu na drugi wymaga tylko jednego kliknięcia.";
$MESS["DISK_HELP_9"] = "Tworzenie Nowego Dokumentu";
?>