<? $this->initCss(); ?>

<?php $this->headScript()->captureStart(Zend_View_Helper_Placeholder_Container_Abstract::APPEND, 'text/javascript', array('charset'=>'UTF-8')); ?>
/* BX_DEBUG_INFO */
var SCRUMBAN = <?= $this->modelOutput($this->jsConstants(), true) ?>;
<? $this->headScript()->captureEnd() ?>

<?php $this->headScript()->captureStart(Zend_View_Helper_Placeholder_Container_Abstract::APPEND, 'text/javascript', array('charset'=>'UTF-8', 'magic' => false)) ?>
/* BX_DEBUG_INFO */
var baseStaticPath = '<?= SCRUMBAN_PATH_STATIC ?>';
var projectList = <?= $this->modelOutput($this->projectList) ?>;
var lastProjects = <?= $this->modelOutput($this->lastProjects); ?>;
var userFeed = <?= $this->modelOutput($this->userFeed); ?>;
<?php $this->headScript()->captureEnd() ?>

<? $this->initJs(); ?>

<div id="kanban" class="settings-board">

    <div class="frameBorder">
        <div class="header">
            <div class="fixer">
                <div class="left">
                    <a href="javascript:void(0)" class="launchpad-link js-launchpad-link"><i class="ico-launchpad"></i></a>
                    <div class="settings-title">Настройки<i class="ico-settings-big"></i></div>
                </div>
            </div>
        </div>

        <div class="leftPadder"></div>
        <div class="rightPadder"></div>

    </div>

    <div class="frameInner">

        <div class="support-settings">
            <form action="" method="post">
                <h1>Режим технической поддержки</h1>
                <div class="selects-wrapper">
                    <div class="support-select">
                        <label for="customer_deps">Подразделения заказчиков</label>
                        <select name="customer_deps[]" id="customer_deps" multiple>
                            <? foreach ($this->depsList as $dep) : ?>
                                <option value="<?= $dep['ID']; ?>"<?= in_array($dep['ID'], $this->customerDeps) ? ' selected' : ''; ?>><?= $dep['NAME']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="support-select">
                        <label for="manager_deps">Подразделения менеджеров</label>
                        <select name="manager_deps[]" id="manager_deps" multiple>
                            <? foreach ($this->depsList as $dep) : ?>
                                <option value="<?= $dep['ID']; ?>"<?= in_array($dep['ID'], $this->managerDeps) ? ' selected' : ''; ?>><?= $dep['NAME']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                </div>
                <button type="submit" class="fat-green-button">Сохранить</button>
            </form>
        </div>

        <div class="clear"></div>
    </div>

</div>


<div id="ejs">
    <?= $this->partial('ejs/launchpad.ejs'); ?>
</div>
