<div class="landosik" id="kanban-updated">
    <div class="content">
        <div class="link">
            <div class="close" onclick="kanbanUpdated.close();return false;"></div>

            <img src="<?= SCRUMBAN_PATH_STATIC; ?>/pictures/landosik-crm.png" height="100%">

            <div class="text">
                <h2><?= $this->t('KANBAN_UPDATED'); ?></h2>
                <div class="slogan"><?= $this->t('KANBAN_UPDATED_SLOGAN'); ?></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var kanbanUpdated = {
        close: function() {
            var el = document.getElementById('kanban-updated');
            el.parentElement.removeChild(el);
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '<?= $this->url(array('projectId' => $this->projectId), 'close-update-kanban-notify'); ?>');
            xhr.send();
        },
        open: function() {
            document.getElementById('kanban-updated').classList.add('visible');
            document.getElementById('kanban-updated').getElementsByClassName('js-to-owner')[0].href =
                window.SCRUMBAN.routeList.user.profile24.replace('#id#', '<?= $this->ownerId ?>');
        }
    };

    SCRUMBAN.jQuery(function(){
        kanbanUpdated.open();
    });
</script>
