<? $userModel = new Model_Db_Backend_User();
$isCustomer = $userModel->getCurrentUser()->IS_CUSTOMER; ?>
<div id="scrumbanLaunchpad">
    <a href="javascript:void(0)" class="launchpad-close js-close-launchpad"><i class="ico ico-close"></i></a>
    <div class="inner-wrapper">
        <div class="launchpad-title"><?= $this->t('LAUNCHPAD_TITLE'); ?></div>
        <div class="search-row">
            <input type="text" name="search_query" class="js-search-input" placeholder="<?= $this->t('LAUNCHPAD_SEARCH_PH'); ?>"/>
            <a href="javascript:void(0)" class="clear-input js-clear-input"><i class="ico-clear">&nbsp;</i></a>
        </div>
        <div class="body projects-block js-projects-block">
            <div class="links">
                <div class="big-block">
                    <a <? if (Model_Db_Backend_User::isExtranetUser()) :
                            ?>href="javascript:void(0)" class="link big disabled"<?
                        else :
                            ?>href="<?= $this->url(array(), 'projects-index'); ?>" class="link big"<?
                        endif; ?>>
                        <i class="ico ico-desktop">&nbsp;</i>
                            <span class="link-label">
                                <span class="link-text"><?= $this->t('LAUNCHPAD_DESKTOP_TITLE'); ?></span>
                                <small><?= $this->t('LAUNCHPAD_DESKTOP_SUBTITLE'); ?></small>
                            </span>
                    </a>
                    <? $crmLink = Model_Db_Backend_Options::isModuleInstalled('sibirix.crm') ? $this->backend()->getCrmBoardLink() : $this->backend()->getCrmMpLink(); ?>
                    <a href="<?= $crmLink; ?>" target="_blank" class="link big">
                        <i class="ico ico-crm">&nbsp;</i>
                        <span class="link-label">
                            <span class="link-text"><?= $this->t('LAUNCHPAD_CRM_TITLE'); ?></span>
                            <small><?= $this->t('LAUNCHPAD_CRM_SUBTITLE'); ?></small>
                        </span>
                    </a>
                </div>


                <?= $this->render('_block/launchpad-settings-link.phtml'); ?>
                <a href="<?= Model_Db_Backend_File::getDocFileLink(); ?>" class="link" target="_blank">
                    <i class="ico ico-docs">&nbsp;</i>
                        <span class="link-label">
                            <span class="link-text"><?= $this->t('LAUNCHPAD_DOC_TITLE'); ?></span>
                            <small><?= $this->t('LAUNCHPAD_DOC_SUBTITLE'); ?></small>
                        </span>
                </a>
                <a href="http://scrumban.helpdesk.sibirix.ru/" class="link" target="_blank">
                    <i class="ico ico-support">&nbsp;</i>
                        <span class="link-label">
                            <span class="link-text"><?= $this->t('LAUNCHPAD_SUPPORT_TITLE'); ?></span>
                            <small><?= $this->t('LAUNCHPAD_SUPPORT_SUBTITLE'); ?></small>
                        </span>
                </a>
                <? if (!$isCustomer) : ?>
                    <?= $this->render('_block/launchpad-to-kp-link.phtml'); ?>
                <? endif; ?>
            </div>
            <div class="right-col js-right-col"></div>
        </div>
        <div class="body search-results-block js-search-results-block"></div>
        <div class="loader js-search-loader" style="text-align: center;"><canvas class="shortLoader"></canvas></div>
    </div>
</div>
