<?
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_ACTIVITY"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création d'activité dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_COMPANY"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de société dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_CONTACT"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de prospect dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_DEAL"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de transaction dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_INVOICE"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de facture dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_COMMENT_CRM_ENTITY_COMMENT_LEAD"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de prospect dans le flux d'activités#A_END#.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_ACTIVITY"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création d'activité dans le Flux d'activités.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_COMPANY"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création de société dans le Flux d'activités.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_CONTACT"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création de contact dans le Flux d'activités.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_DEAL"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création de transaction dans le Flux d'activités.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_INVOICE"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création de facture dans le Flux d'activités.";
$MESS["SONET_COMMENTAUX_CREATETASK_POST_CRM_LEAD"] = "La tâche \"#TASK_NAME#\" a été créée à partir d'une entrée de notification de mise à jour/création de prospect dans le Flux d'activités.";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ACTIVITY"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création d'activité dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_COMPANY"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création de société dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_CONTACT"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création de contact dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_DEAL"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création de prospect dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_ACTIVITY"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création d'activité dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_COMPANY"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de société dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_CONTACT"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de contact dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_DEAL"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de transaction dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_INVOICE"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de facture dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_ENTITY_COMMENT_LEAD"] = "La tâche a été créée à partir d'un #A_BEGIN#commentaire laissé sur une entrée de notification de mise à jour/création de prospect dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_INVOICE"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création de facture dans le flux d'activités#A_END#";
$MESS["SONET_EXT_COMMENTAUX_CREATE_TASK_CRM_LEAD"] = "La tâche a été créée à partir d'une #A_BEGIN#entrée de notification de mise à jour/création de prospect dans le flux d'activités#A_END#";
?>