<div class="settingsMenu jsSettingsMenu">
    <div class="popupOpener"><i></i><span><?= $this->t('TOP_MENU_SETTINGS') ?></span></div>
    <div class="popup settingsMenuPopup">
        <div class="group column-card-view">
            <h6><?= $this->t('TASK_CARDS_VIEW') ?></h6>
            <ul>
                <li><label><input type="radio" class="jsCardViewType" name="card-view-type" value="task-view-full" checked><?= $this->t('VIEW_FULL') ?></label></li>
                <li><label><input type="radio" class="jsCardViewType" name="card-view-type" value="task-view-short"><?= $this->t('VIEW_COMPACT') ?></label></li>
                <li class='gallery'><label><input type='checkbox' name='' class="jsShowImages"><?= $this->t('SETTINGS_SHOW_IMAGES') ?></label></li>
                <?/*li class='resp'><label><input type='checkbox' name='' class="jsShowResp"><?= $this->t('SETTINGS_SHOW_RESPONSIBLES_ALWAYS') ?></label></li*/?>
                <? $userModel = new Model_Db_Backend_User();
                $user = $userModel->getCurrentUser();
                if (!$userModel->IS_CUSTOMER) : ?>
                    <li class='column-stats'><label><input type='checkbox' name='' class="jsColumnStats"><?= $this->t('SETTINGS_SHOW_COLUMNS_STATS') ?></label></li>
                <? endif; ?>
                <? if ($this->board->GROUP_ID && $this->board->CURRENT_USER->IS_MANAGER) : ?>
                    <li class='column-stats'><label><input type='checkbox' name='' class="jsToggleCustomEstimate"><?= $this->t('SETTINGS_SHOW_CUSTOM_ESTIMATE') ?></label></li>
                    <li class='column-stats'><label><input type='checkbox' name='' class="jsToggleDevEstimate"><?= $this->t('SETTINGS_SHOW_DEV_ESTIMATE') ?></label></li>
                <? endif; ?>
            </ul>
        </div>

        <div class="group column-card-view">
            <h6><?= $this->t('TASK_MULTITASK_VIEW') ?></h6>
            <ul>
                <li><label><input type="radio" class="jsMultitaskView" name="multitask-view-type" value="full" checked><?= $this->t('VIEW_FULL') ?></label></li>
                <li><label><input type="radio" class="jsMultitaskView" name="multitask-view-type" value="short"><?= $this->t('VIEW_COMPACT') ?></label></li>
            </ul>
        </div>

        <div class="group">
            <h6><?= $this->t('SHOW_COLUMNS') ?></h6>
            <ul class="availableColumnList"></ul>
        </div>

        <div class="group jsSorting">
            <h6><?= $this->t('SETTINGS_SORTING') ?></h6>
            <ul>
                <li><label><input type="radio" name="sorting" value="importance"><?= $this->t('SETTINGS_SORTING_IMPORTANCE') ?></label></li>
                <li><label><input type="radio" name="sorting" value="manual"><?= $this->t('SETTINGS_SORTING_DND') ?></label></li>
            </ul>
        </div>
        <div class="group group-button">
            <a class="button thin jsKanbanSettingsButton" href="javascript:void(0)"><?= $this->t('BOARD_SETTINGS') ?></a>
            <a class="button thin jsShowChartsButton" href="javascript:void(0)"><?= $this->t('BOARD_CHARTS') ?></a>
            <? if ($this->board->GROUP_ID && $this->board->PROJECT && $this->board->PROJECT->SUPPORT_ENABLED) : ?>
                <a class="button thin" href="<?= $this->url(array('projectId' => $this->board->GROUP_ID), 'projects-reports'); ?>"><?= $this->t('PROJECT_REPORTS') ?></a>
            <? endif; ?>
        </div>
    </div>
</div>
