<div id="landosik" style="display: block;">
    <div class="content">
        <a href="<?= $this->backend()->getCrmMpLink(); ?>" target="_blank">
            <div class="close" onclick="Landosik.close();return false;"></div>

            <img src="<?= SCRUMBAN_PATH_STATIC; ?>/pictures/landosik-crm.png" height="100%">

            <div class="text">
                <h2><?= $this->t('LANDOSIK_CRM_TITLE'); ?> <span class="highlight"><?= $this->t('LANDOSIK_FREE'); ?></span></h2>

                <div class="slogan"><?= $this->t('LANDOSIK_CRM_SLOGAN'); ?></div>
            </div>
        </a>
    </div>
</div>
<script type="text/javascript">
    var Landosik = {
        close: function() {
            document.getElementById('landosik').remove();
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '<?= $this->url(array(), 'close-crm-notify'); ?>');
            xhr.send();
        }
    }
</script>
